### ISSUE TITLE
Update-addressbook / new-addressbook emailAddress, isSender, isDestination

### ISSUE THREAD

**Issue by nascentt** [desjardinsm/RicohAddressBook#1]
The module is great, but you can only add or update entries with folderpath not emailaddress or sender/destination boolean.

I tried adding the parameter and property to update-addressbookentry myself but get invalid operation trying to use it.

**Comment by desjardinsm** [comment]
We don't usually do email sending in our environment, so that wasn't something I set up when I wrote this. This is from a while ago, and I don't really handle that kind of stuff anymore in our organization, so I am a bit rusty with the parameter names that Ricoh is expecting.

Does this commit work for you? It seems to work in my limited testing, but that's only on one scanner, and I haven't actually tried scanning to it yet.

**Edit**: Actually, there are some issues with the current implementation when trying to set isDestination or isSender to false.

**Comment by desjardinsm** [comment]
Okay, I fixed some other things. Again, it seems to work for me, but I haven't been able to test it too thoroughly.

Do you know of any use-case where isDestination could be false?

**Comment by nascentt** [comment]
In our organization isDestination always is true.

Many thanks for your assistance with this. I'll test it out and confirm tomorrow

**Comment by nascentt** [comment]
Thank you so much, the updated code in the commit works.  I'm now able to add and update address book entries with the email address.

**Comment by desjardinsm** [comment]
Okay, good to hear. Make sure you use the latest commit, because I did notice a bug when adding or updating in bulk using the pipeline, where values bleed between invocations if they weren't supplied on each object passed in. I pushed a workaround this morning, although the syntax for IsSender and IsDestination have changed: rather than just being a switch (`-IsSender`), they now require an explicit value (`-IsSender $true`, `-IsSender $false`).

Also, there is a weird interaction between Frequent, Title1, Title2, and Title3, since they are all on the same property on the device, so setting the value for one of them actually resets the value of the others, if you didn't also set a value for those.
