### ISSUE TITLE
Error when adding address book entry with "long name" longer than 16 characters

### ISSUE THREAD

**Issue by nascentt** [desjardinsm/RicohAddressBook#2]
It seems "long name" maps to "key display" which has a max length of 16 characters. 
This means the long name has to be shorter than the regular name (which can be 20 characters)

So using Add-AddressbookEntry I can provide a -Name up to 20 characters without returning an error but the long name will return an error if it's longer than 16 characters?

I get an error UDirectory_Bad_Object from Invoke-SoapRequest when running Add-AddressBookEntry when the -long name exceeds 16 characters but -Name is ok up to 20 characters.

Not sure if the add-addressbookentry command maps the parameters to the wrong API parameters or there's something else going on. But -longname looks like it should be -keydisplay

**Comment by desjardinsm** [comment]
You're right, "longName" is the internal name of the property on the scanner, so I made the parameter "-LongName", but it is displayed as Key Display in the UI. I should have provided a different name for that parameter. I can make an alias for that and provide max length validation.

I just did some preliminary testing, and found other properties that should have had length validation:
* Name (20)
* KeyDisplay (16)
* FolderScanPath (256)
* EmailAddress (128)

**Comment by nascentt** [comment]
Good catch I found out name was limited to 20 but not the others.

**Comment by desjardinsm** [comment]
Okay, give that last set of commits a try. It should now be called -KeyDisplay (but -LongName is provided as an alias), with maximum lengths on those four properties mentioned.

**Comment by nascentt** [comment]
The validation works well, although I noticed I now get an error that the following are required: frequent, title1 title2 or title3 (commit 6916dd2).  But this was not previously a requirement and I was able to add and update entries without setting any of those previously?

I presume it's related to https://github.com/desjardinsm/RicohAddressBook/issues/1#issuecomment-1896459956 ?

Edit: ok playing with this more on the web UI it does indeed state either one title or frequent is required, but the web API  automatically adds frequent (unless that was your code?). So I guess your https://github.com/desjardinsm/RicohAddressBook/issues/1#issuecomment-1896459956 commit is correct despite the api working for me without it.  

I see you have Get-Title1Tag. How about calling that on the first character of Name? If no title or frequency provided?

**Comment by desjardinsm** [comment]
Yes, sorry, I did make some breaking changes there...

The web UI does require at least one of them (but interestingly, the API endpoint lets you submit without any), and if you don't supply at least one, the only way to find that entry is by the registration number, since it won't show up under any of the tabs on the scanner. The web UI does default to having Frequent be on, but currently the parameter in `Add-AddressBookEntry` is a switch, so I can't really make that default to true.

I could make that a boolean and default to true (which I think would most closely match the remote UI), or make it true if nothing else is provided, or just use `Get-Title1Tag` on the first character of Name (I didn't go that route in the first place because I didn't really want to presume how people want to sort their entries; maybe they want it by last name). I'm not really sure which would be best, to be honest, but I'm leaning towards the first option with it as a boolean defaulted to true.

**Comment by desjardinsm** [comment]
@nascentt, give 0a449ef5ad7efef99dcf4f4b88dc6178838d6792 a try. It changes the way `-Frequent` works to default it to true, like the web UI (but it leaves the error message if Frequent is set to false and no other tag value is provided).

**Comment by nascentt** [comment]
That seems like a good compromise!  Note that I get both the "At least of the following" (not at least ONE of the following) as well as a COMMON_BAD_PARAMETER from the server.
When using add-addressbookentry -frequent $false

**Comment by desjardinsm** [comment]
Whoops, good catch on those.

I think the COMMON_BAD_PARAMETER is coming from the fact that errors inside of the process block are non-terminating (so that if this is in a pipeline, the other entries can still be added). However, if all entries fail, then it tries to submit without anything in its body (or more specifically in the `<propListList />` element), which gives that "COMMON_BAD_PARAMETER" error. That should be fixed now (54c64d4aff7c86fb289d2bba7e22fd8253e22b95) to only try to submit if there is at least one element to submit.

The wording on that error is fixed in the next commit (7a5ea4670ef258beb2355dd2a637a742c83f1890).

**Comment by nascentt** [comment]
Thanks that looks good now. 
Appreciate the fast and effective fixes!

**Comment by desjardinsm** [comment]
Glad to hear. And thank you for your help in testing and improving this!

**Comment by nascentt** [comment]
I don't want to open an issue/request for this as it isn't important and I don't know if it's possible, but was just wondering if it possible to have a title2 and title2 validated parameters or is it just not something that's easy to determine/vary between printer models?

Just figured I'd suggest in terms of feature completeness.

**Comment by desjardinsm** [comment]
Validated how, @nascentt? I'm not really sure how other printers work, but on the ones we have, Title 2 is 1 through 10 and Title 3 is 1 through 5. They should already be validated with that constraint, as bytes with a ValidateRange attribute with their respective ranges. Do you know of other constraints that they should have? Or whether those are not working correctly?

**Comment by nascentt** [comment]
Ours are also 1-10 and 1-5
I wasn't sure if that was a constant for all printers or not.  Would just be nice to have the parameter value tab complete the same way as title1 does.

Obviously wouldn't want to ask for changes that might break other printers if they have different value ranges.

Just figured I'd mention as a possibility. I primarily use frequent and title1 so it was more as a completeness nice-to-have.
Feel free to disregard the request if there's no set-in-stone confirmation they'll always be 1-10 and 1-5.

**Comment by desjardinsm** [comment]
Ah I see, the autocompletion. They do have the `[ValidateRange()]` on them, so they are already assuming those ranges are correct and the same across printers.

The autocomplete on `-Title1` comes from the fact that the type is set to an enum. The same effect can be achieved using `[ValidateSet()]`, but I didn't really think that necessary because `[ValidateRange()]` already does validation to make sure it is a correct value. I think I could put both attributes on it, for autocompletion's sake, without breaking anything.

**Comment by desjardinsm** [comment]
Hi @nascentt, can you try [releases/tag/v1.1.0-pre.1](https://github.com/desjardinsm/RicohAddressBook/releases/tag/v1.1.0-pre.1) to see if this works?

I also applied this to the `-DisplayPriority` parameter, since that's also a range of 1–10. Also, the autocompletion looks a bit weird because it's treating those values as if they were text, so it sorts the "10" between the "1" and the "2".

**Comment by nascentt** [comment]
Sorry the GitHub app sometimes fails to notify me of new notifications so I just saw this.  Using the new 1.1.0 pre.1 indeed looks to successfully provide the parameter inputs.

However something I failed to consider is with the input validation it's not possible to clear fields (regardless of this change as "" and $null don't meet validation. I'll create a separate issue for that as it's unrelated to anything in this issue. You may close this, many thanks.

**Comment by desjardinsm** [comment]
Okay, thanks. I'll close this and publish 1.1.0 at some point. It is actually possible to clear the Title fields, but it's not super intuitive as to why. I've posted in that other issue some of the background information that causes it to behave that way.
